# generate_data.py
import pandas as pd
import numpy as np

# Set a seed for reproducibility
np.random.seed(42)

# Positive Keywords (100) - Paste your array here
positive_keywords = [ "amazing", "fantastic", "awesome", "great", "excellent", "wonderful", "perfect", "outstanding", 
    "superb", "brilliant", "fabulous", "terrific", "stellar", "phenomenal", "incredible", 
    "impressive", "remarkable", "splendid", "marvelous", "exceptional", "delightful", "pleasing", 
    "satisfying", "thrilling", "enjoyable", "lovely", "charming", "captivating", "engaging", 
    "refreshing", "invigorating", "uplifting", "inspiring", "heartwarming", "joyful", "blissful", 
    "euphoric", "ecstatic", "radiant", "glorious", "divine", "heavenly", "miraculous", "magical", 
    "enchanting", "mesmerizing", "breathtaking", "stunning", "gorgeous", "beautiful", "elegant", 
    "graceful", "classy", "sophisticated", "polished", "flawless", "impeccable", "pristine", 
    "spotless", "immaculate", "crisp", "sharp", "vibrant", "lively", "dynamic", "energetic", 
    "vivid", "colorful", "radiant", "glowing", "shiny", "sparkling", "gleaming", "lustrous", 
    "dazzling", "glittering", "twinkling", "scintillating", "effervescent", "bubbly", "cheerful", 
    "optimistic", "hopeful", "promising", "encouraging", "motivating", "empowering", "reassuring", 
    "comforting", "soothing", "calming", "relaxing", "peaceful", "serene", "tranquil", "harmonious", 
    "balanced", "wholesome", "nutritious", "healthy", "healing", "rejuvenating", "revitalizing", 
    "restorative", "renewing", "refreshing"]

# Negative Keywords (100) - Paste your array here
negative_keywords = ["terrible", "awful", "horrible", "bad", "poor", "disappointing", "unpleasant", "dreadful", 
    "atrocious", "abysmal", "lousy", "subpar", "inferior", "mediocre", "unsatisfactory", "frustrating", 
    "annoying", "irritating", "aggravating", "infuriating", "maddening", "exasperating", "disgusting", 
    "revolting", "repulsive", "nauseating", "sickening", "offensive", "vile", "disgraceful", 
    "shameful", "appalling", "deplorable", "pitiful", "pathetic", "lamentable", "regrettable", 
    "unfortunate", "unlucky", "tragic", "heartbreaking", "devastating", "crushing", "demoralizing", 
    "discouraging", "disheartening", "depressing", "gloomy", "bleak", "dismal", "grim", "hopeless", 
    "desperate", "dire", "harrowing", "distressing", "upsetting", "troubling", "worrisome", "alarming", 
    "frightening", "scary", "terrifying", "horrifying", "shocking", "startling", "jarring", "unsettling", 
    "disturbing", "uncomfortable", "awkward", "embarrassing", "humiliating", "mortifying", "shameful", 
    "disrespectful", "insulting", "offensive", "rude", "crude", "vulgar", "obscene", "lewd", "filthy", 
    "dirty", "grimy", "stained", "tainted", "contaminated", "polluted", "toxic", "hazardous", "dangerous", 
    "harmful", "damaging", "destructive", "ruinous", "catastrophic", "calamitous", "disastrous", 
    "devastating", "crippling", "debilitating", "exhausting", "draining", "weakening", "sapping", 
    "enervating", "fatiguing", "tiring", "wearisome", "tedious", "boring", "monotonous", "repetitive"]

# Positive Statements (100) - Paste your array here
positive_statements = [ "I love this product! It's amazing and works perfectly.",
    "This is the best purchase I've ever made. Highly recommended!",
    "The quality is outstanding, and it exceeded my expectations.",
    "I'm so happy with this product. It's worth every penny.",
    "This product is fantastic! It has made my life so much easier.",
    "I can't believe how great this product is. It's a game-changer!",
    "The performance is excellent, and I'm very satisfied.",
    "This product is worth the investment. It's top-notch!",
    "I'm thrilled with this purchase. It's exactly what I needed.",
    "The design is beautiful, and it works flawlessly.",
    "This product is a must-have. It's simply perfect!",
    "I'm impressed with the quality and functionality of this product.",
    "This product is a lifesaver. It's made my daily tasks so much easier.",
    "I'm so glad I bought this. It's been a great addition to my life.",
    "This product is incredible! It's everything I hoped for and more.",
    "The customer service was excellent, and the product is amazing.",
    "I'm extremely satisfied with this product. It's a great value.",
    "This product is a dream come true. It's perfect in every way.",
    "I'm so pleased with this purchase. It's been a great experience.",
    "This product is a gem. It's worth every penny!",
    "I'm blown away by how good this product is. It's a must-buy!",
    "This product is a winner. It's exceeded all my expectations.",
    "I'm so happy with this product. It's been a great investment.",
    "This product is a game-changer. It's made my life so much better.",
    "I'm thrilled with this product. It's been a great addition to my routine.",
    "This product is a lifesaver. It's made my tasks so much easier.",
    "I'm so glad I found this product. It's been a great help.",
    "This product is a gem. It's worth every penny!",
    "I'm blown away by how good this product is. It's a must-buy!",
    "This product is a winner. It's exceeded all my expectations.",
    "I'm so happy with this product. It's been a great investment.",
    "This product is a game-changer. It's made my life so much better.",
    "I'm thrilled with this product. It's been a great addition to my routine.",
    "This product is a lifesaver. It's made my tasks so much easier.",
    "I'm so glad I found this product. It's been a great help.",
    "This product is a gem. It's worth every penny!",
    "I'm blown away by how good this product is. It's a must-buy!",
    "This product is a winner. It's exceeded all my expectations.",
    "I'm so happy with this product. It's been a great investment.",
    "This product is a game-changer. It's made my life so much better.",
    "I'm thrilled with this product. It's been a great addition to my routine.",
    "This product is a lifesaver. It's made my tasks so much easier.",
    "I'm so glad I found this product. It's been a great help.",
    "This product is a gem. It's worth every penny!",
    "I'm blown away by how good this product is. It's a must-buy!",
    "This product is a winner. It's exceeded all my expectations.",
    "I'm so happy with this product. It's been a great investment.",
    "This product is a game-changer. It's made my life so much better.",
    "I'm thrilled with this product. It's been a great addition to my routine.",
    "This product is a lifesaver. It's made my tasks so much easier.",
    "I'm so glad I found this product. It's been a great help.",
    "This product is a gem. It's worth every penny!",
    "I'm blown away by how good this product is. It's a must-buy!",
    "This product is a winner. It's exceeded all my expectations.",
    "I'm so happy with this product. It's been a great investment.",
    "This product is a game-changer. It's made my life so much better.",
    "I'm thrilled with this product. It's been a great addition to my routine.",
    "This product is a lifesaver. It's made my tasks so much easier.",
    "I'm so glad I found this product. It's been a great help.",
    "This product is a gem. It's worth every penny!",
    "I'm blown away by how good this product is. It's a must-buy!",
    "This product is a winner. It's exceeded all my expectations.",
    "I'm so happy with this product. It's been a great investment.",
    "This product is a game-changer. It's made my life so much better.",
    "I'm thrilled with this product. It's been a great addition to my routine.",
    "This product is a lifesaver. It's made my tasks so much easier.",
    "I'm so glad I found this product. It's been a great help.",
    "This product is a gem. It's worth every penny!",
    "I'm blown away by how good this product is. It's a must-buy!",
    "This product is a winner. It's exceeded all my expectations.",
    "I'm so happy with this product. It's been a great investment.",
    "This product is a game-changer. It's made my life so much better.",
    "I'm thrilled with this product. It's been a great addition to my routine.",
    "This product is a lifesaver. It's made my tasks so much easier.",
    "I'm so glad I found this product. It's been a great help.",
    "This product is a gem. It's worth every penny!",
    "I'm blown away by how good this product is. It's a must-buy!",
    "This product is a winner. It's exceeded all my expectations.",
    "I'm so happy with this product. It's been a great investment.",
    "This product is a game-changer. It's made my life so much better.",
    "I'm thrilled with this product. It's been a great addition to my routine.",
    "This product is a lifesaver. It's made my tasks so much easier.",
    "I'm so glad I found this product. It's been a great help.",
    "This product is a gem. It's worth every penny!",
    "I'm blown away by how good this product is. It's a must-buy!",
    "This product is a winner. It's exceeded all my expectations.",
    "I'm so happy with this product. It's been a great investment.",
    "This product is a game-changer. It's made my life so much better.",
    "I'm thrilled with this product. It's been a great addition to my routine.",
    "This product is a lifesaver. It's made my tasks so much easier.",
    "I'm so glad I found this product. It's been a great help.",
    "This product is a gem. It's worth every penny!",
    "I'm blown away by how good this product is. It's a must-buy!",
    "This product is a winner. It's exceeded all my expectations.",
    "I'm so happy with this product. It's been a great investment.",
    "This product is a game-changer. It's made my life so much better.",
    "I'm thrilled with this product. It's been a great addition to my routine.",
    "This product is a lifesaver. It's made my tasks so much easier.",
    "I'm so glad I found this product. It's been a great help."
]

# Negative Statements (100) - Paste your array here
negative_statements = ["I hate this product. It's terrible and doesn't work at all.",
    "This is the worst purchase I've ever made. Avoid it!",
    "The quality is awful, and it broke after just one use.",
    "I'm so disappointed with this product. It's a waste of money.",
    "This product is a complete failure. It doesn't work as advertised.",
    "I can't believe how bad this product is. It's a scam!",
    "The performance is terrible, and I regret buying it.",
    "This product is not worth the money. It's a rip-off!",
    "I'm extremely unhappy with this purchase. It's a disaster.",
    "The design is ugly, and it doesn't function properly.",
    "This product is a nightmare. It's been nothing but trouble.",
    "I'm frustrated with the poor quality of this product.",
    "This product is a waste of time and money. Avoid it!",
    "I'm so annoyed with this product. It's been a huge letdown.",
    "This product is a joke. It's not worth the price.",
    "The customer service was terrible, and the product is awful.",
    "I'm extremely dissatisfied with this product. It's a scam.",
    "This product is a disaster. It's broken and unusable.",
    "I'm so frustrated with this purchase. It's been a nightmare.",
    "This product is a rip-off. It's not worth the money!",
    "I'm blown away by how bad this product is. It's a scam!",
    "This product is a failure. It's not worth the price.",
    "I'm so unhappy with this product. It's been a huge disappointment.",
    "This product is a joke. It's not worth the money.",
    "I'm frustrated with the poor quality of this product.",
    "This product is a waste of time and money. Avoid it!",
    "I'm so annoyed with this product. It's been a huge letdown.",
    "This product is a scam. It's not worth the price.",
    "I'm extremely dissatisfied with this product. It's a disaster.",
    "This product is a nightmare. It's been nothing but trouble.",
    "I'm so frustrated with this purchase. It's been a nightmare.",
    "This product is a rip-off. It's not worth the money!",
    "I'm blown away by how bad this product is. It's a scam!",
    "This product is a failure. It's not worth the price.",
    "I'm so unhappy with this product. It's been a huge disappointment.",
    "This product is a joke. It's not worth the money.",
    "I'm frustrated with the poor quality of this product.",
    "This product is a waste of time and money. Avoid it!",
    "I'm so annoyed with this product. It's been a huge letdown.",
    "This product is a scam. It's not worth the price.",
    "I'm extremely dissatisfied with this product. It's a disaster.",
    "This product is a nightmare. It's been nothing but trouble.",
    "I'm so frustrated with this purchase. It's been a nightmare.",
    "This product is a rip-off. It's not worth the money!",
    "I'm blown away by how bad this product is. It's a scam!",
    "This product is a failure. It's not worth the price.",
    "I'm so unhappy with this product. It's been a huge disappointment.",
    "This product is a joke. It's not worth the money.",
    "I'm frustrated with the poor quality of this product.",
    "This product is a waste of time and money. Avoid it!",
    "I'm so annoyed with this product. It's been a huge letdown.",
    "This product is a scam. It's not worth the price.",
    "I'm extremely dissatisfied with this product. It's a disaster.",
    "This product is a nightmare. It's been nothing but trouble.",
    "I'm so frustrated with this purchase. It's been a nightmare.",
    "This product is a rip-off. It's not worth the money!",
    "I'm blown away by how bad this product is. It's a scam!",
    "This product is a failure. It's not worth the price.",
    "I'm so unhappy with this product. It's been a huge disappointment.",
    "This product is a joke. It's not worth the money.",
    "I'm frustrated with the poor quality of this product.",
    "This product is a waste of time and money. Avoid it!",
    "I'm so annoyed with this product. It's been a huge letdown.",
    "This product is a scam. It's not worth the price.",
    "I'm extremely dissatisfied with this product. It's a disaster.",
    "This product is a nightmare. It's been nothing but trouble.",
    "I'm so frustrated with this purchase. It's been a nightmare.",
    "This product is a rip-off. It's not worth the money!",
    "I'm blown away by how bad this product is. It's a scam!",
    "This product is a failure. It's not worth the price.",
    "I'm so unhappy with this product. It's been a huge disappointment.",
    "This product is a joke. It's not worth the money.",
    "I'm frustrated with the poor quality of this product.",
    "This product is a waste of time and money. Avoid it!",
    "I'm so annoyed with this product. It's been a huge letdown.",
    "This product is a scam. It's not worth the price.",
    "I'm extremely dissatisfied with this product. It's a disaster.",
    "This product is a nightmare. It's been nothing but trouble.",
    "I'm so frustrated with this purchase. It's been a nightmare.",
    "This product is a rip-off. It's not worth the money!",
    "I'm blown away by how bad this product is. It's a scam!",
    "This product is a failure. It's not worth the price.",
    "I'm so unhappy with this product. It's been a huge disappointment.",
    "This product is a joke. It's not worth the money.",
    "I'm frustrated with the poor quality of this product.",
    "This product is a waste of time and money. Avoid it!",
    "I'm so annoyed with this product. It's been a huge letdown.",
    "This product is a scam. It's not worth the price.",
    "I'm extremely dissatisfied with this product. It's a disaster.",
    "This product is a nightmare. It's been nothing but trouble.",
    "I'm so frustrated with this purchase. It's been a nightmare.",
    "This product is a rip-off. It's not worth the money!",
    "I'm blown away by how bad this product is. It's a scam!",
    "This product is a failure. It's not worth the price.",
    "I'm so unhappy with this product. It's been a huge disappointment.",
    "This product is a joke. It's not worth the money.",
    "I'm frustrated with the poor quality of this product.",
    "This product is a waste of time and money. Avoid it!",
    "I'm so annoyed with this product. It's been a huge letdown.",
    "This product is a scam. It's not worth the price.",
    "I'm extremely dissatisfied with this product. It's a disaster.",
    "This product is a nightmare. It's been nothing but trouble.",
    "I'm so frustrated with this purchase. It's been a nightmare.",
    "This product is a rip-off. It's not worth the money!",
    "I'm blown away by how bad this product is. It's a scam!",
    "This product is a failure. It's not worth the price.",
    "I'm so unhappy with this product. It's been a huge disappointment.",
    "This product is a joke. It's not worth the money.",
    "I'm frustrated with the poor quality of this product.",
    "This product is a waste of time and money. Avoid it!",
    "I'm so annoyed with this product. It's been a huge letdown.",
    "This product is a scam. It's not worth the price.",
    "I'm extremely dissatisfied with this product. It's a disaster.",
    "This product is a nightmare. It's been nothing but trouble.",
    "I'm so frustrated with this purchase. It's been a nightmare.",
    "This product is a rip-off. It's not worth the money!",
    "I'm blown away by how bad this product is. It's a scam!",
    "This product is a failure. It's not worth the price.",
    "I'm so unhappy with this product. It's been a huge disappointment.",
    "This product is a joke. It's not worth the money.",
    "I'm frustrated with the poor quality of this product.",
    "This product is a waste of time and money. Avoid it!",
    "I'm so annoyed with this product. It's been a huge letdown.",
    "This product is a scam. It's not worth the price.",
    "I'm extremely dissatisfied with this product. It's a disaster.",
    "This product is a nightmare. It's been nothing but trouble.",
    "I'm so frustrated with this purchase. It's been a nightmare.",
    "This product is a rip-off. It's not worth the money!",
    "I'm blown away by how bad this product is. It's a scam!",
    "This product is a failure. It's not worth the price.",
    "I'm so unhappy with this product. It's been a huge disappointment.",
    "This product is a joke. It's not worth the money.",
    "I'm frustrated with the poor quality of this product.",
    "This product is a waste of time and money. Avoid it!",
    "I'm so annoyed with this product. It's been a huge letdown.",
    "This product is a scam. It's not worth the price.",
    "I'm extremely dissatisfied with this product. It's a disaster.",
    "This product is a nightmare. It's been nothing but trouble."]

# Generate synthetic data
n_samples = 10000
reviews = []
sentiments = []

for _ in range(n_samples):
    if np.random.rand() > 0.5:
        # Positive review
        sentiment = "positive"
        # Randomly choose between a statement or a keyword-based review
        if np.random.rand() > 0.5:
            review = np.random.choice(positive_statements)
        else:
            keywords = np.random.choice(positive_keywords, size=3, replace=False)
            review = f"I love this product! It's {keywords[0]}, {keywords[1]}, and {keywords[2]}."
    else:
        # Negative review
        sentiment = "negative"
        # Randomly choose between a statement or a keyword-based review
        if np.random.rand() > 0.5:
            review = np.random.choice(negative_statements)
        else:
            keywords = np.random.choice(negative_keywords, size=3, replace=False)
            review = f"I hate this product. It's {keywords[0]}, {keywords[1]}, and {keywords[2]}."
    
    reviews.append(review)
    sentiments.append(sentiment)

# Create a DataFrame
data = pd.DataFrame({'review': reviews, 'sentiment': sentiments})

# Save the data to a CSV file
data.to_csv('customer_reviews.csv', index=False)